### ISSUE TITLE
Always use cargo install -f

### ISSUE THREAD

**Issue by lu-zero** [sifis-home/sifis-generate#39]
Otherwise you get this problem

https://github.com/sifis-home/wot-rust/runs/6419990099?check_suite_focus=true

```
Run cargo install cargo-fuzz
    Updating crates.io index
error: binary `cargo-fuzz` already exists in destination
Add --force to overwrite
Error: Process completed with exit code 101.
```

**Comment by Luni-4** [comment]
Fixed in https://github.com/sifis-home/sifis-generate/commit/e421580bf4ad892831e6b2c06073a267560cf26b
