### ISSUE TITLE
Optimize build for AddressSanitizer

### ISSUE THREAD

**Issue by dodomorandi** [sifis-home/sifis-generate#53]
Tests run using AddressSanitizer can be _very_ slow, enabling optimizations would improve CI time quite a lot.

However, it is a good idea to keep the `debug-assertions` active, therefore I would recommend to add `-Copt-level=3` to `RUSTFLAGS` instead of using the `--release` parameter.

**Comment by Luni-4** [comment]
Fixed in [2a601ca](https://github.com/sifis-home/sifis-generate/commit/2a601ca5b0a3069e4e0ab2f9f7cb7d2bfe92d95f)
