### ISSUE TITLE
CI script for windows installs cargo-fuzz

### ISSUE THREAD

**Issue by arpad-m** [sifis-home/sifis-generate#56]
The autogenerated CI script for windows installs cargo-fuzz even though cargo-fuzz is not used, like it is used on macos or linux:

https://github.com/sifis-home/sifis-generate/blob/e11aa0766218a816af4f3272f2e3644ea08c8a00/templates/cargo/github-windows.yml#L95-L98

It should maybe be removed.

**Comment by Luni-4** [comment]
Fixed in [e861aaa](https://github.com/sifis-home/sifis-generate/commit/e861aaa762ba883c92faf117a072daf1ff7dc158)
