### ISSUE TITLE
action-rs/* are unmaintained

### ISSUE THREAD

**Issue by lu-zero** [sifis-home/sifis-generate#57]
the toolchain and clippy actions already found a new home apparently.
we should replace asap.

**Comment by Luni-4** [comment]
Only `cargo clippy` action is left

**Comment by lu-zero** [comment]
https://github.com/actions-rs-plus/clippy-check is the replacement

**Comment by lu-zero** [comment]
See https://github.com/actions-rs-plus/clippy-check/issues/105 to use a specific snapshot

**Comment by Luni-4** [comment]
Fixed in 2ec9edc9e5d0bb76ae3fd31d6752bc79ec419289
